import { Task } from "@/app/types/task";

export const taskColumnsCompact = [
  { key: "taskTitle", label: "Task" },
  { key: "taskType", label: "Type" },
  { key: "priority", label: "Priority" },
  { key: "status", label: "Status" },
  { key: "assignedDeveloper", label: "Dev" },
  { key: "finalEstimate", label: "Est." },
];
export const dummyTasks: Task[] = [
  {
    id: "1",
    taskTitle: "Implement Dark Mode Toggle",
    taskDescription: "Add dark/light mode switch in header with persistence in localStorage",
    acceptanceCriteria:
      "- Toggle works on click\n- Preference saved in localStorage\n- Applies instantly across all pages\n- Matches Figma design",
    project: "aceflow",
    module: "auth",
    taskType: "feature",
    priority: "high",
    tag: "tag1",
    status: "in-progress",
    assignedDeveloper: "john",
    reviewer: "mike",
    qaOwner: "alex",
    tlEstimate: "8",
    allowDeveloperEstimate: true,
    developerEstimate: "10",
    finalEstimate: "10",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "2025-12-09",
    dueDate: "2025-12-15",
    storyPoints: "5",
    labels: "ui,frontend",
    comments: "Design approved by Sarah",
    attachments: "",
    createdAt: "2025-12-09T10:30:00Z",
  },
  {
    id: "2",
    taskTitle: "Fix Login API 401 Error on Mobile",
    taskDescription:
      "Users getting unauthorized error after app background > foreground on iOS/Android",
    acceptanceCriteria:
      "- Token refresh works automatically\n- No login loop\n- Works on both iOS & Android",
    project: "aceflow",
    module: "auth",
    taskType: "bug",
    priority: "critical",
    tag: "tag2",
    status: "review",
    assignedDeveloper: "sarah",
    reviewer: "emma",
    qaOwner: "nina",
    tlEstimate: "4",
    allowDeveloperEstimate: false,
    developerEstimate: "",
    finalEstimate: "4",
    blocked: true,
    blockedReason: "Waiting for backend token endpoint fix",
    dependsOnTasks: "7",
    startDate: "2025-12-07",
    dueDate: "2025-12-10",
    storyPoints: "3",
    labels: "mobile,bug",
    comments: "Blocked until backend team fixes refresh token",
    attachments: "screenshot-mobile-login.mp4",
    createdAt: "2025-12-07T14:20:00Z",
  },
  {
    id: "3",
    taskTitle: "Add Task Dependencies UI",
    taskDescription: "Allow dragging tasks to create dependency arrows in board view",
    acceptanceCriteria:
      "- Visual arrow between tasks\n- Save dependencies in DB\n- Block task if predecessor not done",
    project: "aceflow",
    module: "core",
    taskType: "feature",
    priority: "medium",
    tag: "tag3",
    status: "pending",
    assignedDeveloper: "john",
    reviewer: "mike",
    qaOwner: "alex",
    tlEstimate: "16",
    allowDeveloperEstimate: true,
    developerEstimate: "20",
    finalEstimate: "20",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "",
    dueDate: "2025-12-25",
    storyPoints: "13",
    labels: "kanban,ux",
    comments: "",
    attachments: "",
    createdAt: "2025-12-09T09:15:00Z",
  },
  {
    id: "4",
    taskTitle: "Update Dashboard Charts Library",
    taskDescription: "Migrate from Chart.js to ApexCharts for better performance",
    acceptanceCriteria: "- All existing charts work\n- Responsive on mobile\n- Dark mode support",
    project: "aceflow",
    module: "dashboard",
    taskType: "improvement",
    priority: "low",
    tag: "tag1",
    status: "completed",
    assignedDeveloper: "sarah",
    reviewer: "emma",
    qaOwner: "nina",
    tlEstimate: "12",
    allowDeveloperEstimate: false,
    developerEstimate: "",
    finalEstimate: "12",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "2025-11-20",
    dueDate: "2025-12-05",
    storyPoints: "8",
    labels: "refactor,charts",
    comments: "Completed and deployed",
    attachments: "",
    createdAt: "2025-11-18T11:00:00Z",
  },
  {
    id: "5",
    taskTitle: "Add Export to CSV Feature",
    taskDescription: "Button to export current filtered task list as CSV",
    acceptanceCriteria:
      "- Exports visible columns only\n- Proper headers\n- Works with filters applied",
    project: "aceflow",
    module: "tasks",
    taskType: "feature",
    priority: "medium",
    tag: "tag4",
    status: "pending",
    assignedDeveloper: "",
    reviewer: "",
    qaOwner: "",
    tlEstimate: "6",
    allowDeveloperEstimate: false,
    developerEstimate: "",
    finalEstimate: "6",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "",
    dueDate: "",
    storyPoints: "5",
    labels: "export,table",
    comments: "Waiting for assignment",
    attachments: "",
    createdAt: "2025-12-08T16:45:00Z",
  },
  {
    id: "6",
    taskTitle: "Memory Leak in Task Detail Modal",
    taskDescription: "Task detail modal causing memory usage to increase over time",
    acceptanceCriteria:
      "- Memory stable after opening/closing modal 50 times\n- No event listeners left behind",
    project: "aceflow",
    module: "tasks",
    taskType: "bug",
    priority: "high",
    tag: "tag2",
    status: "in-progress",
    assignedDeveloper: "john",
    reviewer: "mike",
    qaOwner: "alex",
    tlEstimate: "8",
    allowDeveloperEstimate: true,
    developerEstimate: "12",
    finalEstimate: "12",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "2025-12-08",
    dueDate: "2025-12-12",
    storyPoints: "8",
    labels: "performance,bug",
    comments: "Found issue with useEffect cleanup",
    attachments: "memory-profile.png",
    createdAt: "2025-12-08T10:00:00Z",
  },
  {
    id: "7",
    taskTitle: "Backend: Refresh Token Endpoint",
    taskDescription: "Implement proper refresh token rotation as per OAuth2 best practices",
    acceptanceCriteria:
      "- New refresh token on each use\n- Old tokens invalidated\n- Works with mobile clients",
    project: "aceflow",
    module: "auth",
    taskType: "task",
    priority: "critical",
    tag: "tag3",
    status: "in-progress",
    assignedDeveloper: "sarah",
    reviewer: "emma",
    qaOwner: "nina",
    tlEstimate: "16",
    allowDeveloperEstimate: false,
    developerEstimate: "",
    finalEstimate: "16",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "2025-12-05",
    dueDate: "2025-12-11",
    storyPoints: "13",
    labels: "backend,security",
    comments: "High priority for mobile fix",
    attachments: "",
    createdAt: "2025-12-05T13:30:00Z",
  },
  {
    id: "8",
    taskTitle: "Improve Task Search Performance",
    taskDescription: "Search is slow when >5000 tasks",
    acceptanceCriteria:
      "- Search under 300ms for 10k tasks\n- Debounced input\n- Client-side indexing if needed",
    project: "aceflow",
    module: "tasks",
    taskType: "improvement",
    priority: "medium",
    tag: "tag1",
    status: "pending",
    assignedDeveloper: "john",
    reviewer: "mike",
    qaOwner: "alex",
    tlEstimate: "12",
    allowDeveloperEstimate: true,
    developerEstimate: "10",
    finalEstimate: "10",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "",
    dueDate: "2025-12-20",
    storyPoints: "8",
    labels: "performance,search",
    comments: "Consider Fuse.js or Web Workers",
    attachments: "",
    createdAt: "2025-12-09T11:20:00Z",
  },
  {
    id: "9",
    taskTitle: "Add Bulk Actions to Task Table",
    taskDescription: "Select multiple tasks and change status/assign in bulk",
    acceptanceCriteria: "- Checkbox selection\n- Bulk status update\n- Bulk assign developer",
    project: "aceflow",
    module: "tasks",
    taskType: "feature",
    priority: "high",
    tag: "tag4",
    status: "pending",
    assignedDeveloper: "",
    reviewer: "",
    qaOwner: "",
    tlEstimate: "10",
    allowDeveloperEstimate: false,
    developerEstimate: "",
    finalEstimate: "10",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "",
    dueDate: "",
    storyPoints: "8",
    labels: "table,ux",
    comments: "Requested by team leads",
    attachments: "bulk-actions-figma.png",
    createdAt: "2025-12-09T15:00:00Z",
  },
  {
    id: "task-010",
    taskTitle: "Update Dependencies & Security Audit",
    taskDescription: "Run npm audit fix and update all packages to latest compatible versions",
    acceptanceCriteria:
      "- No high/critical vulnerabilities\n- All tests passing\n- Update lockfile",
    project: "aceflow",
    module: "core",
    taskType: "task",
    priority: "medium",
    tag: "tag2",
    status: "completed",
    assignedDeveloper: "sarah",
    reviewer: "mike",
    qaOwner: "nina",
    tlEstimate: "4",
    allowDeveloperEstimate: false,
    developerEstimate: "",
    finalEstimate: "4",
    blocked: false,
    blockedReason: "",
    dependsOnTasks: "",
    startDate: "2025-12-06",
    dueDate: "2025-12-06",
    storyPoints: "2",
    labels: "maintenance,security",
    comments: "Done in morning standup",
    attachments: "",
    createdAt: "2025-12-06T09:00:00Z",
  },
];
