import { ModuleTableData } from "@/app/types/module";

export const moduleColumns = [
  { key: "projectType", label: "Project Name" },
  { key: "projectName", label: "Module Name" },
  { key: "authType", label: "Authentication Type" },
  { key: "priority", label: "Prioriry" },
  { key: "status", label: "Status" },
];

export const moduleData: ModuleTableData[] = [
  {
    id: "1",
    projectType: "project1",
    projectName: "User Authentication Module",
    authType: "auth1",
    priority: "priority1",
    status: "active",
  },
  {
    id: "2",
    projectType: "project2",
    projectName: "Dashboard & Analytics",
    authType: "auth2",
    priority: "priority2",
    status: "active",
  },
  {
    id: "3",
    projectType: "project1",
    projectName: "Payment Integration",
    authType: "auth3",
    priority: "priority1",
    status: "active",
  },
  {
    id: "4",
    projectType: "project3",
    projectName: "File Management System",
    authType: "auth1",
    priority: "priority3",
    status: "inactive",
  },
  {
    id: "5",
    projectType: "project4",
    projectName: "Notification Engine",
    authType: "auth4",
    priority: "priority2",
    status: "active",
  },
  {
    id: "6",
    projectType: "project2",
    projectName: "Role & Permission Manager",
    authType: "auth1",
    priority: "priority1",
    status: "active",
  },
  {
    id: "7",
    projectType: "project5",
    projectName: "API Gateway Module",
    authType: "auth5",
    priority: "priority4",
    status: "active",
  },
  {
    id: "8",
    projectType: "project1",
    projectName: "Reporting & Export",
    authType: "auth2",
    priority: "priority3",
    status: "inactive",
  },
  {
    id: "9",
    projectType: "project3",
    projectName: "Real-time Chat Service",
    authType: "auth1",
    priority: "priority2",
    status: "active",
  },
  {
    id: "10",
    projectType: "project4",
    projectName: "Backup & Recovery Module",
    authType: "auth3",
    priority: "priority5",
    status: "active",
  },
];
