import { ProjectsTableData } from "@/app/types/projects";

export const projectColumns = [
  { key: "projectName", label: "Project Name" },
  { key: "projectCode", label: "Project Code" },
  { key: "projectType", label: "Project Type" },
  { key: "clientName", label: "Client Name" },
  { key: "projectCategory", label: "Project Category" },
  { key: "projectOwner", label: "Project Owner" },
  { key: "status", label: "Status" },
  { key: "startDate", label: "Start Date" },
  { key: "endDate", label: "End Date" },
  { key: "billingModel", label: "Billing Model" },
  { key: "description", label: "Description" },
  { key: "techStack", label: "Tech Stack" },
];

export const projectsData: ProjectsTableData[] = [
  {
    id: 1,
    projectName: "Website Redesign",
    projectCode: "WR-123",
    projectType: "Web Development",
    clientName: "ABC Corp",
    projectCategory: "Project Category 1",
    projectOwner: "John Doe",
    techStack: [
      { key: "html", label: "HTML" },
      { key: "css", label: "CSS" },
      { key: "js", label: "JavaScript" },
      { key: "react", label: "React" },
    ],
    startDate: "2025-01-01",
    endDate: "2025-06-30",
    billingModel: "Fixed Price",
    description: "A complete website redesign for ABC Corp, including new UX/UI design and development using React.",
    status: "In Progress",
  },
  {
    id: 2,
    projectName: "Mobile App Launch",
    projectCode: "MA-456",
    projectType: "Mobile Development",
    clientName: "XYZ Ltd",
    projectCategory: "Project Category 1",
    projectOwner: "Jane Smith",
    techStack: [
      { key: "flutter", label: "Flutter" },
      { key: "dart", label: "Dart" },
      { key: "firebase", label: "Firebase" },
    ],
    startDate: "2025-02-01",
    endDate: "2025-09-30",
    billingModel: "Hourly Rate",
    description: "Development of a cross-platform mobile app using Flutter and Firebase for XYZ Ltd.",
    status: "Pending",
  },
  {
    id: 3,
    projectName: "E-Commerce Platform",
    projectCode: "EC-789",
    projectType: "E-Commerce",
    clientName: "LMN Enterprises",
    projectCategory: "Project Category 1",
    projectOwner: "Alice Johnson",
    techStack: [
      { key: "node", label: "Node.js" },
      { key: "mongodb", label: "MongoDB" },
      { key: "express", label: "Express" },
      { key: "angular", label: "Angular" },
    ],
    startDate: "2025-03-01",
    endDate: "2025-12-31",
    billingModel: "Revenue Share",
    description: "Building a scalable e-commerce platform for LMN Enterprises with Node.js, Express, and MongoDB.",
    status: "Not Started",
  },
];
