import { ProjectsTableData } from "@/app/types/projects";

export const projectColumns = [
  { key: "projectName", label: "Project Name" },
  { key: "projectCode", label: "Project Code" },
  { key: "projectType", label: "Project Type" },
  { key: "clientName", label: "Client Name" },
  { key: "projectCategory", label: "Project Category" },
  { key: "projectOwner", label: "Project Owner" },
  { key: "status", label: "Status" },
  { key: "startDate", label: "Start Date" },
  { key: "endDate", label: "End Date" },
  { key: "billingModel", label: "Billing Model" },
  { key: "description", label: "Description" },
  // { key: "techStack", label: "Tech Stack" },
];

export const projectsData: ProjectsTableData[] = [
  {
    id: "1",
    projectName: "Willa Brown",
    projectCode: "WB-2025-001",
    projectType: "project1",
    clientName: "Uta Pennington",
    projectCategory: "project1",
    projectOwner: "Sarah Connor",
    owner: "John Reese",
    techStack: ["python", "vuejs", "springBoot"],
    startDate: "2025-01-15",
    endDate: "2025-08-30",
    billingModel: "billing1",
    description: "Enterprise dashboard with real-time analytics",
    status: "active",
  },
  // Baaki 9 records bhi same values se bana diye hain
  {
    id: "2",
    projectName: "AceFlow Mobile App",
    projectCode: "AF-MOB-2025",
    projectType: "project2",
    clientName: "AceFlow Inc.",
    projectCategory: "project2",
    projectOwner: "Mike Chen",
    owner: "Lisa Wang",
    techStack: ["react", "nodejs"],
    startDate: "2025-03-01",
    endDate: "2025-12-31",
    billingModel: "billing2",
    description: "Internal mobile app",
    status: "active",
  },
  {
    id: "3",
    projectName: "Quantum Banking Platform",
    projectCode: "QBP-2024-09",
    projectType: "project1",
    clientName: "Quantum Finance Ltd",
    projectCategory: "project3",
    projectOwner: "David Miller",
    owner: "Emma Wilson",
    techStack: ["java", "springBoot", "angular"],
    startDate: "2024-09-10",
    endDate: "2026-03-15",
    billingModel: "billing1",
    description: "Next-gen banking system",
    status: "active",
  },
  {
    id: "4",
    projectName: "HealthSync Pro",
    projectCode: "HSP-2025",
    projectType: "project1",
    clientName: "MediCare Solutions",
    projectCategory: "project4",
    projectOwner: "Rachel Green",
    owner: "Dr. Alex Turner",
    techStack: ["c#/.net", "react"],
    startDate: "2025-02-01",
    endDate: "2025-11-30",
    billingModel: "billing1",
    description: "Patient management platform",
    status: "inactive",
  },
  {
    id: "5",
    projectName: "E-Commerce Revamp",
    projectCode: "ECR-2025-02",
    projectType: "project1",
    clientName: "ShopGlobal Inc.",
    projectCategory: "project5",
    projectOwner: "James Park",
    owner: "Nina Patel",
    techStack: ["django", "vuejs"],
    startDate: "2025-04-01",
    endDate: "2025-10-30",
    billingModel: "billing2",
    description: "Marketplace redesign",
    status: "active",
  },
  {
    id: "6",
    projectName: "AI Content Generator",
    projectCode: "AIG-2025",
    projectType: "project2",
    clientName: "AceFlow Labs",
    projectCategory: "project1",
    projectOwner: "Tom Hardy",
    owner: "Prof. Alan Grant",
    techStack: ["python", "go"],
    startDate: "2025-01-20",
    endDate: "2025-09-15",
    billingModel: "billing3",
    description: "AI content tool",
    status: "active",
  },
  {
    id: "7",
    projectName: "Logistics Tracker",
    projectCode: "LT-2025-03",
    projectType: "project1",
    clientName: "SwiftLogix",
    projectCategory: "project2",
    projectOwner: "Kevin Brooks",
    owner: "Maria Lopez",
    techStack: ["go", "react"],
    startDate: "2025-05-10",
    endDate: "2026-02-28",
    billingModel: "billing1",
    description: "Real-time tracking",
    status: "inactive",
  },
  {
    id: "8",
    projectName: "HR Management System",
    projectCode: "HRMS-2025",
    projectType: "project1",
    clientName: "PeopleFirst Corp",
    projectCategory: "project3",
    projectOwner: "Linda Carter",
    owner: "Robert Kim",
    techStack: ["c#/.net", "angular"],
    startDate: "2024-11-01",
    endDate: "2025-07-31",
    billingModel: "billing1",
    description: "HRIS system",
    status: "active",
  },
  {
    id: "9",
    projectName: "Smart City Dashboard",
    projectCode: "SCD-2025-01",
    projectType: "project1",
    clientName: "MetroGov",
    projectCategory: "project4",
    projectOwner: "Ahmed Khan",
    owner: "City Administrator",
    techStack: ["nodejs", "react"],
    startDate: "2025-06-01",
    endDate: "2026-06-01",
    billingModel: "billing1",
    description: "IoT city dashboard",
    status: "active",
  },
  {
    id: "10",
    projectName: "EdTech Learning Platform",
    projectCode: "EDU-2025",
    projectType: "project1",
    clientName: "LearnBright Academy",
    projectCategory: "project5",
    projectOwner: "Sophie Martin",
    owner: "Prof. Daniel Lee",
    techStack: ["rubyOnRails", "react"],
    startDate: "2025-03-15",
    endDate: "2025-12-20",
    billingModel: "billing2",
    description: "LMS with gamification",
    status: "active",
  },
];
