// src/app/components/dummydata/DummyData.ts

export const dashboardData = {
  metadata: {
    user: {
      name: "John Patrick Doe",
      title: "Senior Software Engineer",
      location: "New York, USA",
      reportingManager: "Jane Smith",
      totalProjects: 12,
      totalAllocatedHours: 460,
      totalTimeSpent: 350,
      totalBlockedHours: 65,
    },
  },

  projects: [
    { id: "all", name: "All Projects" },
    { id: "platform-rearch", name: "Platform Re-architecture" },
    { id: "mobile-feature-x", name: "Mobile App Feature X" },
    { id: "internal-tools", name: "Internal Tools Optimization" },
  ],

  tasks: [
    {
      id: "t1",
      title: "Backend microservice development",
      projectId: "platform-rearch",
      projectName: "Platform Re-architecture",
      module: "Backend",
      status: "blocked",
      estimate: 30,
      spent: 10,
      blocked: true,
      date: "2025-12-03",
      isRecent: true,
    },
    {
      id: "t2",
      title: "Fix Performance Bug in API Gateway",
      projectId: "platform-rearch",
      projectName: "Platform Re-architecture",
      module: "API",
      status: "blocked",
      estimate: 15,
      spent: 6,
      blocked: true,
      date: "2025-12-02",
      isRecent: true,
    },
    {
      id: "t3",
      title: "Optimize database queries",
      projectId: "internal-tools",
      projectName: "Internal Tools Optimization",
      module: "Database",
      status: "completed",
      estimate: 10,
      spent: 12,
      blocked: false,
      date: "2025-12-01",
      isRecent: true,
    },
    {
      id: "t4",
      title: "Implement Authentication Flow",
      projectId: "platform-rearch",
      projectName: "Platform Re-architecture",
      module: "Security",
      status: "in-progress",
      estimate: 20,
      spent: 12,
      blocked: false,
      date: "2025-12-04",
    },
    {
      id: "t5",
      title: "Refactor old database queries",
      projectId: "internal-tools",
      projectName: "Internal Tools Optimization",
      module: "Backend",
      status: "in-progress",
      estimate: 30,
      spent: 13,
      blocked: true,
      date: "2025-11-28",
    },
    {
      id: "t6",
      title: "Integrate Third-party API",
      projectId: "mobile-feature-x",
      projectName: "Mobile App Feature X",
      module: "Integration",
      status: "in-progress",
      estimate: 18,
      spent: 7,
      blocked: false,
      date: "2025-12-04",
    },
    {
      id: "t7",
      title: "Frontend component library update",
      projectId: "internal-tools",
      projectName: "Internal Tools Optimization",
      module: "UI/UX",
      status: "in-progress",
      estimate: 15,
      spent: 8,
      blocked: false,
      date: "2025-11-30",
    },
    {
      id: "t8",
      title: "Deploy new auth service",
      projectId: "platform-rearch",
      projectName: "Platform Re-architecture",
      module: "DevOps",
      status: "completed",
      estimate: 8,
      spent: 6,
      blocked: false,
      date: "2025-11-25",
    },
  ],

  timeEntries: [
    { taskTitle: "Implement User Authentication Flow", hours: 4.5, date: "2025-12-04" },
    { taskTitle: "Working on OAuth Integration", hours: 6, date: "2025-12-03" },
    { taskTitle: "Develop Frontend for User Profile Page", hours: 6, date: "2025-12-02" },
    { taskTitle: "Initial layout and component setup", hours: 2, date: "2025-12-01" },
    { taskTitle: "Fix Performance Bug in API Gateway", hours: 3.5, date: "2025-11-30" },
  ],

  activityFeed: [
    {
      user: "Jane Smith",
      action: "commented on",
      target: "Implement User Auth Flow",
      time: "2 hours ago",
    },
    { user: "Jane Smith", action: "changed status to", target: "In Progress", time: "5 hours ago" },
    {
      user: "Yesterday",
      action: "assigned",
      target: "Develop Frontend for User Profile Page",
      assignee: "John Doe",
      time: "1 day ago",
    },
    { user: "John Doe", action: "commented on", target: "Fix Performance Bug", time: "2 days ago" },
  ],

  productivityScoreTrend: [
    { date: "Nov 20", score: 96 },
    { date: "Nov 21", score: 92 },
    { date: "Nov 22", score: 88 },
    { date: "Nov 23", score: 94 },
    { date: "Nov 24", score: 90 },
    { date: "Nov 25", score: 85 },
    { date: "Nov 26", score: 89 },
    { date: "Nov 27", score: 93 },
    { date: "Nov 28", score: 87 },
    { date: "Nov 29", score: 91 },
    { date: "Nov 30", score: 88 },
    { date: "Dec 01", score: 92 },
    { date: "Dec 02", score: 90 },
    { date: "Dec 03", score: 89 },
    { date: "Dec 04", score: 93 },
  ],

  stuckVsAllocated: [
    { module: "Security", allocated: 60, stuck: 12 },
    { module: "Database", allocated: 85, stuck: 28 },
    { module: "API", allocated: 110, stuck: 35 },
    { module: "UI/UX", allocated: 75, stuck: 8 },
    { module: "DevOps", allocated: 50, stuck: 15 },
  ],

  stuckHoursTrend: [
    { date: "Nov 05", hours: 12 },
    { date: "Nov 10", hours: 18 },
    { date: "Nov 15", hours: 15 },
    { date: "Nov 20", hours: 22 },
    { date: "Nov 25", hours: 28 },
    { date: "Nov 30", hours: 35 },
    { date: "Dec 03", hours: 42 },
    { date: "Dec 04", hours: 38 },
  ],

  activeProjects: [
    {
      projectId: "platform-rearch",
      name: "Platform Re-architecture",
      lead: "Lead Developer",
      tasks: 19,
      allocated: 200,
      spent: 142,
    },
    {
      projectId: "mobile-feature-x",
      name: "Mobile App Feature X",
      lead: "Backend Developer",
      tasks: 8,
      allocated: 80,
      spent: 60,
    },
    {
      projectId: "internal-tools",
      name: "Internal Tools Optimization",
      lead: "Fullstack Engineer",
      tasks: 14,
      allocated: 180,
      spent: 148,
    },
  ],
};

// src/data/dashboardOverviewData.ts
// src/components/dummydata/DummyData.ts

export const dashboardOverviewData = {
  keyMetrics: {
    totalActiveProjects: 4,
    totalAssignedTasks: 95,
    upcomingTasks: 7,
    activeEmployees: { total: 43, day: 29, night: 14 },
  },

  projects: [
    { id: "all", name: "All Projects" },
    { id: "alpha", name: "Project Alpha" },
    { id: "beta", name: "Beta Core" },
    { id: "delta", name: "Delta Mobile" },
    { id: "gamma", name: "Gamma Portal" },
  ],

  projectHealth: [
    { id: "alpha", name: "Project Alpha", health: 88, status: "Healthy", delayedTasks: 3 },
    { id: "beta", name: "Beta Core", health: 62, status: "At Risk", delayedTasks: 8 },
    { id: "delta", name: "Delta Mobile", health: 45, status: "Critical", delayedTasks: 14 },
    { id: "gamma", name: "Gamma Portal", health: 95, status: "Healthy", delayedTasks: 1 },
  ],

  recentlyCompletedTasks: [
    {
      id: 1,
      task: "UI Redesign Login Page",
      projectId: "alpha",
      projectName: "Project Alpha",
      assignee: "Amit Sharma",
      completedOn: "2025-12-04",
    },
    {
      id: 2,
      task: "API Integration v2",
      projectId: "beta",
      projectName: "Beta Core",
      assignee: "Priya Singh",
      completedOn: "2025-12-03",
    },
    {
      id: 3,
      task: "Mobile Responsiveness Fix",
      projectId: "delta",
      projectName: "Delta Mobile",
      assignee: "Rahul Verma",
      completedOn: "2025-12-03",
    },
    {
      id: 4,
      task: "Database Migration",
      projectId: "gamma",
      projectName: "Gamma Portal",
      assignee: "Neha Gupta",
      completedOn: "2025-12-02",
    },
    {
      id: 5,
      task: "Payment Gateway Setup",
      projectId: "alpha",
      projectName: "Project Alpha",
      assignee: "Vikash Kumar",
      completedOn: "2025-12-01",
    },
    {
      id: 6,
      task: "Auth Flow Fix",
      projectId: "alpha",
      projectName: "Project Alpha",
      assignee: "Amit Sharma",
      completedOn: "2025-11-28",
    },
    {
      id: 7,
      task: "Cache Implementation",
      projectId: "beta",
      projectName: "Beta Core",
      assignee: "Priya Singh",
      completedOn: "2025-11-25",
    },
  ],

  upcomingDeadlines: [
    {
      task: "Payment Gateway Integration",
      projectId: "alpha",
      projectName: "Project Alpha",
      dueIn: "2 days",
      priority: "High",
      dueDate: "2025-12-10",
    },
    {
      task: "Mobile OTP Flow",
      projectId: "delta",
      projectName: "Delta Mobile",
      dueIn: "3 days",
      priority: "High",
      dueDate: "2025-12-11",
    },
    {
      task: "Analytics Report v2",
      projectId: "beta",
      projectName: "Beta Core",
      dueIn: "5 days",
      priority: "Medium",
      dueDate: "2025-12-13",
    },
    {
      task: "SEO Audit",
      projectId: "gamma",
      projectName: "Gamma Portal",
      dueIn: "6 days",
      priority: "Medium",
      dueDate: "2025-12-14",
    },
  ],

  delayedTasksSummary: [
    {
      id: 1,
      projectId: "alpha",
      projectName: "Project Alpha",
      module: "Payment Gateway",
      totalTasks: 24,
      delayedTasks: 5,
      worstDelay: "12 days",
      responsible: "Vikash Kumar",
    },
    {
      id: 2,
      projectId: "beta",
      projectName: "Beta Core",
      module: "API Integration v2",
      totalTasks: 18,
      delayedTasks: 3,
      worstDelay: "8 days",
      responsible: "Priya Singh",
    },
    {
      id: 3,
      projectId: "delta",
      projectName: "Delta Mobile",
      module: "Mobile Responsiveness",
      totalTasks: 31,
      delayedTasks: 2,
      worstDelay: "6 days",
      responsible: "Rahul Verma",
    },
    {
      id: 4,
      projectId: "gamma",
      projectName: "Gamma Portal",
      module: "Database Migration",
      totalTasks: 15,
      delayedTasks: 1,
      worstDelay: "4 days",
      responsible: "Neha Gupta",
    },
  ],

  taskProgress: [
    { name: "Completed", value: 68, color: "#10b981" },
    { name: "In Progress", value: 20, color: "#3b82f6" },
    { name: "Delayed", value: 7, color: "#ef4444" },
  ],
};
